
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.1.0-community
        ports:
          - name: https-port
            containerPort: 9000
        volumeMounts:
          - name: sonar-data
            mountPath: /opt/sonarqube/data
          - name: sonar-extensions
            mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonar-data
          emptyDir: {}
        - name: sonar-extensions
          emptyDir: {}  
