databaseUpgradeReady: true
artifactory:
  replicaCount: 3
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  persistence:
    enabled: false

postgresql:
  postgresqlPassword: password
  postgresqlExtendedConf:
    maxConnections: 102
  persistence:
    enabled: false
